In [103]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [104]:
df = pd.read_csv("/content/student_placement_synthetic.csv")
df

,branch,college_tier,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,internships,projects_count,certifications,hackathons,open_source_contributions,extracurriculars,placement_status,salary_package_lpa
0,ECE,Tier-3,6.70,0,7.6,4.4,49.5,3.7,6.4,0.3,1,4,4,3,2,1,1,14.75
1,Chemical,Tier-2,5.70,0,5.4,7.9,72.0,8.3,6.3,1.9,0,4,0,0,0,0,0,NaN
2,EE,Tier-2,7.19,0,5.6,6.8,79.1,7.4,4.4,5.2,1,3,2,1,2,0,1,19.06
3,CE,Tier-2,6.48,0,5.2,3.1,48.4,5.0,1.1,6.7,1,4,3,0,0,0,0,NaN
4,CSE,Tier-2,6.71,1,5.9,4.7,61.2,4.3,2.7,2.8,1,2,0,3,0,1,1,13.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,IT,Tier-3,6.08,0,3.1,5.4,67.4,4.3,9.1,3.8,2,3,2,0,0,3,0,NaN
99996,IT,Tier-3,7.46,0,4.8,6.8,59.5,7.6,5.6,2.4,1,2,3,0,1,0,1,16.58
99997,EE,Tier-2,7.94,0,4.9,9.1,55.1,6.1,3.5,5.2,0,2,1,0,1,2,1,17.24
99998,ME,Tier-3,6.63,0,5.0,8.0,65.0,5.7,6.2,0.2,1,4,2,0,0,1,1,17.01
99999,ECE,Tier-1,7.00,0,2.8,5.3,64.5,5.7,5.7,3.4,0,2,2,2,0,1,1,14.98

In [105]:
df.head()

,branch,college_tier,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,internships,projects_count,certifications,hackathons,open_source_contributions,extracurriculars,placement_status,salary_package_lpa
0,ECE,Tier-3,6.70,0,7.6,4.4,49.5,3.7,6.4,0.3,1,4,4,3,2,1,1,14.75
1,Chemical,Tier-2,5.70,0,5.4,7.9,72.0,8.3,6.3,1.9,0,4,0,0,0,0,0,NaN
2,EE,Tier-2,7.19,0,5.6,6.8,79.1,7.4,4.4,5.2,1,3,2,1,2,0,1,19.06
3,CE,Tier-2,6.48,0,5.2,3.1,48.4,5.0,1.1,6.7,1,4,3,0,0,0,0,NaN
4,CSE,Tier-2,6.71,1,5.9,4.7,61.2,4.3,2.7,2.8,1,2,0,3,0,1,1,13.42

In [106]:
df.shape

(100000, 18)

In [107]:
df.columns

Index(['branch', 'college_tier', 'cgpa', 'backlogs', 'coding_skills',
       'dsa_score', 'aptitude_score', 'communication_skills', 'ml_knowledge',
       'system_design', 'internships', 'projects_count', 'certifications',
       'hackathons', 'open_source_contributions', 'extracurriculars',
       'placement_status', 'salary_package_lpa'],
      dtype='object')

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   branch                     100000 non-null  int64
 1   college_tier               100000 non-null  object
 2   cgpa                       100000 non-null  float64
 3   backlogs                   100000 non-null  int64
 4   coding_skills              100000 non-null  float64
 5   dsa_score                  100000 non-null  float64
 6   aptitude_score             100000 non-null  float64
 7   communication_skills       100000 non-null  float64
 8   ml_knowledge               100000 non-null  float64
 9   system_design              100000 non-null  float64
 10  internships                100000 non-null  int64
 11  projects_count             100000 non-null  int64
 12  certifications             100000 non-null  int64
 13  hackathons                 100000 non-null  int64
 14  open_source_contributions  100000 non-null  int64
 15  extracurriculars           100000 non-null  int64
 16  placement_status           100000 non-null  int64
 17  salary_package_lpa         68475 non-null   float64
dtypes: float64(8), int64(9), object(1)
memory usage: 13.7+ MB

In [117]:
df.isnull().sum()

branch                           0
college_tier                     0
cgpa                             0
backlogs                         0
coding_skills                    0
dsa_score                        0
aptitude_score                   0
communication_skills             0
ml_knowledge                     0
system_design                    0
internships                      0
projects_count                   0
certifications                   0
hackathons                       0
open_source_contributions        0
extracurriculars                 0
placement_status                 0
salary_package_lpa           31525
dtype: int64

In [118]:
df.describe()

,branch,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,internships,projects_count,certifications,hackathons,open_source_contributions,extracurriculars,placement_status,salary_package_lpa
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,68475.000000
mean,2.902560,7.206381,0.547010,5.995147,5.500711,64.990511,5.990614,4.508752,4.008210,1.095040,2.397280,1.49985,0.745840,0.450990,1.151100,0.684750,17.308014
std,1.958837,0.925235,0.862727,1.496302,1.781961,11.990892,1.496552,1.968278,1.778405,0.940264,1.242829,1.11407,0.884189,0.671061,0.965162,0.464618,2.601041
min,0.000000,4.000000,0.000000,1.000000,1.000000,20.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,6.880000
25%,1.000000,6.580000,0.000000,5.000000,4.300000,56.800000,5.000000,3.200000,2.800000,0.000000,1.000000,1.00000,0.000000,0.000000,0.000000,0.000000,15.530000
50%,3.000000,7.210000,0.000000,6.000000,5.500000,65.000000,6.000000,4.500000,4.000000,1.000000,2.000000,1.00000,0.000000,0.000000,1.000000,1.000000,17.250000
75%,5.000000,7.830000,1.000000,7.000000,6.700000,73.100000,7.000000,5.900000,5.200000,2.000000,3.000000,2.00000,1.000000,1.000000,2.000000,1.000000,19.040000
max,6.000000,10.000000,3.000000,10.000000,10.000000,100.000000,10.000000,10.000000,10.000000,3.000000,5.000000,4.00000,3.000000,2.000000,3.000000,1.000000,28.330000

There are two target variables here
1. Classification(placement_status) PLACEMENT PREDICTION
2. Regression(salary_package_lpa) SALARY PREDICTION

In [119]:
df['placement_status'].value_counts()

placement_status
1    68475
0    31525
Name: count, dtype: int64

In [120]:
df['salary_package_lpa'].isnull().sum()

np.int64(31525)

In [121]:
df['branch'].value_counts()

branch
1    25046
5    16065
3    14939
4    12092
6    12008
0    10024
2     9826
Name: count, dtype: int64

In [122]:
df.select_dtypes(include='object').columns

Index(['college_tier'], dtype='object')

In [124]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

categorical_cols = [
    'branch',
    'college_tier'
]

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

In [125]:
df.head()

,branch,college_tier,cgpa,backlogs,coding_skills,dsa_score,aptitude_score,communication_skills,ml_knowledge,system_design,internships,projects_count,certifications,hackathons,open_source_contributions,extracurriculars,placement_status,salary_package_lpa
0,3,2,6.70,0,7.6,4.4,49.5,3.7,6.4,0.3,1,4,4,3,2,1,1,14.75
1,2,1,5.70,0,5.4,7.9,72.0,8.3,6.3,1.9,0,4,0,0,0,0,0,NaN
2,4,1,7.19,0,5.6,6.8,79.1,7.4,4.4,5.2,1,3,2,1,2,0,1,19.06
3,0,1,6.48,0,5.2,3.1,48.4,5.0,1.1,6.7,1,4,3,0,0,0,0,NaN
4,1,1,6.71,1,5.9,4.7,61.2,4.3,2.7,2.8,1,2,0,3,0,1,1,13.42

In [126]:
corr = df.corr()

corr['placement_status'].sort_values(
    ascending=False
)

placement_status             1.000000
cgpa                         0.148932
internships                  0.099967
coding_skills                0.087657
dsa_score                    0.086594
projects_count               0.069900
certifications               0.055636
communication_skills         0.051034
aptitude_score               0.045146
hackathons                   0.033315
open_source_contributions    0.022723
ml_knowledge                 0.002097
branch                      -0.001470
system_design               -0.001583
extracurriculars            -0.004807
backlogs                    -0.058815
college_tier                -0.180052
salary_package_lpa                NaN
Name: placement_status, dtype: float64

In [127]:
X = df.drop(
    ['placement_status', 'salary_package_lpa'],
    axis=1
)

y = df['placement_status']

In [129]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [130]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

In [131]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

lr = LogisticRegression(
    max_iter=5000
)

lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

print("Logistic Regression")
print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print("Precision:", precision_score(y_test, y_pred_lr))
print("Recall:", recall_score(y_test, y_pred_lr))
print("F1 Score:", f1_score(y_test, y_pred_lr))

Logistic Regression
Accuracy: 0.69785
Precision: 0.714967973929655
Recall: 0.9291712303760497
F1 Score: 0.8081160892896834

In [132]:
rf = RandomForestClassifier()

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

print("Random Forest")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf))
print("Recall:", recall_score(y_test, y_pred_rf))
print("F1 Score:", f1_score(y_test, y_pred_rf))

Random Forest
Accuracy: 0.6894
Precision: 0.7114678121290906
Recall: 0.9191675794085432
F1 Score: 0.8020899706894354

In [134]:
!pip install xgboost

from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)

xgb.fit(X_train, y_train)

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.30.7)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [135]:
y_pred_xgb = xgb.predict(X_test)

print("XGBoost")
print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("Precision:", precision_score(y_test, y_pred_xgb))
print("Recall:", recall_score(y_test, y_pred_xgb))
print("F1 Score:", f1_score(y_test, y_pred_xgb))

XGBoost
Accuracy: 0.69555
Precision: 0.7159323188734954
Recall: 0.9207009857612267
F1 Score: 0.805506755677644

Now, Salary **Prediction**

In [137]:
salary_df = df.dropna(subset=['salary_package_lpa'])
X_salary = salary_df.drop(
    ['salary_package_lpa', 'placement_status'],
    axis=1
)

y_salary = salary_df['salary_package_lpa']

In [138]:
X_train_s, X_test_s, y_train_s, y_test_s = train_test_split(
    X_salary,
    y_salary,
    test_size=0.2,
    random_state=42
)

In [140]:
from sklearn.linear_model import LinearRegression

lr_reg = LinearRegression()

lr_reg.fit(X_train_s, y_train_s)

y_pred_lr = lr_reg.predict(X_test_s)

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import numpy as np

print("Linear Regression")

print(
    "MAE:",
    mean_absolute_error(y_test_s, y_pred_lr)
)

print(
    "RMSE:",
    np.sqrt(mean_squared_error(y_test_s, y_pred_lr))
)

print(
    "R2:",
    r2_score(y_test_s, y_pred_lr)
)

Linear Regression
MAE: 0.9869252894770668
RMSE: 1.2354274073053009
R2: 0.7734112865963385

In [141]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# -------------------------------
# Linear Regression
# -------------------------------

lr = LinearRegression()
lr.fit(X_train_s, y_train_s)

y_pred_lr = lr.predict(X_test_s)

print("Linear Regression")
print("MAE:", mean_absolute_error(y_test_s, y_pred_lr))
print("RMSE:", np.sqrt(mean_squared_error(y_test_s, y_pred_lr)))
print("R2:", r2_score(y_test_s, y_pred_lr))

print("\n" + "="*50 + "\n")

# -------------------------------
# Random Forest Regressor
# -------------------------------

rf = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train_s, y_train_s)

y_pred_rf = rf.predict(X_test_s)

print("Random Forest Regressor")
print("MAE:", mean_absolute_error(y_test_s, y_pred_rf))
print("RMSE:", np.sqrt(mean_squared_error(y_test_s, y_pred_rf)))
print("R2:", r2_score(y_test_s, y_pred_rf))

print("\n" + "="*50 + "\n")

# -------------------------------
# Gradient Boosting Regressor
# -------------------------------

gb = GradientBoostingRegressor(
    random_state=42
)

gb.fit(X_train_s, y_train_s)

y_pred_gb = gb.predict(X_test_s)

print("Gradient Boosting Regressor")
print("MAE:", mean_absolute_error(y_test_s, y_pred_gb))
print("RMSE:", np.sqrt(mean_squared_error(y_test_s, y_pred_gb)))
print("R2:", r2_score(y_test_s, y_pred_gb))

print("\n" + "="*50 + "\n")

# -------------------------------
# XGBoost Regressor
# -------------------------------

xgb = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=6,
    random_state=42
)

xgb.fit(X_train_s, y_train_s)

y_pred_xgb = xgb.predict(X_test_s)

print("XGBoost Regressor")
print("MAE:", mean_absolute_error(y_test_s, y_pred_xgb))
print("RMSE:", np.sqrt(mean_squared_error(y_test_s, y_pred_xgb)))
print("R2:", r2_score(y_test_s, y_pred_xgb))

Linear Regression
MAE: 0.9869252894770668
RMSE: 1.2354274073053009
R2: 0.7734112865963385

==================================================

Random Forest Regressor
MAE: 1.0092966593647317
RMSE: 1.266161057274244
R2: 0.7619973930855424

==================================================

Gradient Boosting Regressor
MAE: 0.9703794783244961
RMSE: 1.2178464648002585
R2: 0.779814411849289

==================================================

XGBoost Regressor
MAE: 0.9628936823371032
RMSE: 1.2063537547202465
R2: 0.7839505472500818

In [142]:
import pickle

pickle.dump(lr, open('placement_model.pkl', 'wb'))

pickle.dump(xgb, open('salary_model.pkl', 'wb'))